//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientBillDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientBillDetail()
        {
            this.ClientBillDescriptions = new HashSet<ClientBillDescription>();
            this.LedgerEntries = new HashSet<LedgerEntry>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string DocketCharge { get; set; }
        public string CGST { get; set; }
        public string SGST { get; set; }
        public string IGST { get; set; }
        public string LoadingCharge { get; set; }
        public string Cess { get; set; }
        public string Tax { get; set; }
        public string RoundOff { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string UnloadingCharge { get; set; }
        public string InvoiceNumber { get; set; }
        public string AdvanceAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientBillDescription> ClientBillDescriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LedgerEntry> LedgerEntries { get; set; }
        public virtual ClientDetail ClientDetail { get; set; }
    }
}
