//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientLeadgerDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientLeadgerDetail()
        {
            this.ClientLeadgerDescriptions = new HashSet<ClientLeadgerDescription>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string DocketCharge { get; set; }
        public string CGST { get; set; }
        public string SGST { get; set; }
        public string IGST { get; set; }
        public string LoadingUnloadingCharge { get; set; }
        public string Cess { get; set; }
        public string Tax { get; set; }
        public string RoundOff { get; set; }
    
        public virtual ClientDetail ClientDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientLeadgerDescription> ClientLeadgerDescriptions { get; set; }
    }
}
