//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsigneeDetail
    {
        public int Id { get; set; }
        public string ConsigneeName { get; set; }
        public string ConsigneeAddress { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> Pincode { get; set; }
        public string ContactNo { get; set; }
        public string GSTNo { get; set; }
        public Nullable<int> LRId { get; set; }
    
        public virtual City City { get; set; }
        public virtual LRDetail LRDetail { get; set; }
    }
}
