//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LedgerEntry
    {
        public int Id { get; set; }
        public Nullable<int> LRId { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public Nullable<System.DateTime> LedgerDate { get; set; }
        public string Description { get; set; }
        public string TransactionType { get; set; }
        public Nullable<decimal> TransactionAmount { get; set; }
        public Nullable<decimal> BalenceAmount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual ClientBillDetail ClientBillDetail { get; set; }
        public virtual LRDetail LRDetail { get; set; }
    }
}
