//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LRDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LRDetail()
        {
            this.ClientBillDescriptions = new HashSet<ClientBillDescription>();
            this.ConsigneeDetails = new HashSet<ConsigneeDetail>();
            this.ConsignorDetails = new HashSet<ConsignorDetail>();
            this.LedgerEntries = new HashSet<LedgerEntry>();
            this.ProductDetails = new HashSet<ProductDetail>();
            this.VehicleDriverDetails = new HashSet<VehicleDriverDetail>();
            this.VehicleOwnerDetails = new HashSet<VehicleOwnerDetail>();
        }
    
        public int Id { get; set; }
        public string LRNumber { get; set; }
        public Nullable<System.DateTime> LRDate { get; set; }
        public byte[] OthersAttachment { get; set; }
        public Nullable<int> ServiceOrderId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientBillDescription> ClientBillDescriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsigneeDetail> ConsigneeDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsignorDetail> ConsignorDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LedgerEntry> LedgerEntries { get; set; }
        public virtual ServiceOrderDetail ServiceOrderDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductDetail> ProductDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleDriverDetail> VehicleDriverDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleOwnerDetail> VehicleOwnerDetails { get; set; }
    }
}
