//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetail
    {
        public int Id { get; set; }
        public string ProductDetails { get; set; }
        public string GoodsDetail { get; set; }
        public Nullable<int> NoofUnit { get; set; }
        public string ChargeWeight { get; set; }
        public string InvoiceNo { get; set; }
        public string InvoiceValue { get; set; }
        public string EWayBillNo { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> LRId { get; set; }
    
        public virtual LRDetail LRDetail { get; set; }
    }
}
