//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceOrderPaymentDetail
    {
        public int Id { get; set; }
        public Nullable<int> ServiceOrderId { get; set; }
        public Nullable<decimal> TotalFreight { get; set; }
        public Nullable<decimal> AdvanceFreight { get; set; }
        public Nullable<decimal> BalanceFreight { get; set; }
        public Nullable<decimal> LoadingCharge { get; set; }
        public Nullable<decimal> UnloadingCharge { get; set; }
        public Nullable<decimal> OthersCharge { get; set; }
    
        public virtual ServiceOrderDetail ServiceOrderDetail { get; set; }
    }
}
