//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorLineHaulDetail
    {
        public int Id { get; set; }
        public Nullable<int> FromStateId { get; set; }
        public Nullable<int> ToStateId { get; set; }
        public Nullable<int> VendorId { get; set; }
    
        public virtual State State { get; set; }
        public virtual State State1 { get; set; }
        public virtual VendorDetail VendorDetail { get; set; }
    }
}
